services:
    api:
        build:
            context: ./api
        ports:
            - "8080:8080"
        env_file:
            - ./api/.env.production
        depends_on:
            - mongo
        networks:
            - mypokenetwork

    client:
        build:
            context: ./client
        ports:
            - "3000:80"
        networks:
            - mypokenetwork

    mongo:
        image: mongo:6
        volumes:
            - mongo_data:/data/db
        networks:
            - mypokenetwork
        command: ["mongod", "--quiet", "--logpath", "/dev/null"] # Suppresses logs

volumes:
    mongo_data:

networks:
    mypokenetwork:
        driver: bridge # This is the default driver
