version: "3.8"

services:
    api:
        build:
            context: ./api
        ports:
            - "8080:8080"
        environment:
            - NODE_ENV=production
        networks:
            - mypokenetwork

    client:
        build:
            context: ./client
        ports:
            - "3000:80"
        networks:
            - mypokenetwork

networks:
    mypokenetwork:
        driver: bridge
