version: "3.8"

services:
    api:
        build:
            context: ./api
        ports:
            - "8080:8080"
        env_file:
            - .env.production
        depends_on:
            - mongo
        networks:
            - mypokenetwork

    client:
        build:
            context: ./client
        ports:
            - "3000:3000"
        networks:
            - mypokenetwork

    mongo:
        image: mongo:6
        volumes:
            - mongo_data:/data/db
        networks:
            - mypokenetwork

volumes:
    mongo_data:

networks:
    mypokenetwork:
        driver: bridge
